spring:
  application:
    name: ChickenDirect
  datasource:
    driver-class-name: org.postgresql.Driver
    username: appuser
    password: pirate
    url: jdbc:postgresql://localhost:5432/ChickenDirect
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
management:
  endpoints:
    web:
      exposure:
        include: health, info
  server:
    port: 8090
logging:
  level:
    com.groupa.chickendirectfarm: DEBUG
